import { NextRequest, NextResponse } from "next/server";
import { cookies } from "next/headers";
import { auth } from "@ai-sdk/mcp";
import crypto from "crypto";
import {
  createSouthleftMcpOAuthProvider,
  SOUTHLEFT_COOKIE_STATE,
  SOUTHLEFT_MCP_URL,
} from "@/lib/southleft-mcp-oauth";
import { RedirectError } from "@/lib/figma-mcp-oauth";
import { writeOAuthResult } from "@/lib/oauth-store";

const COOKIE_OAUTH_SESSION = "southleft_oauth_session";

/** Derive origin from the incoming request so cookies stay on the same domain. */
function requestOrigin(request: NextRequest): string {
  const proto = request.headers.get("x-forwarded-proto") || (request.nextUrl.protocol.replace(":", ""));
  const host = request.headers.get("host") || request.nextUrl.host;
  return `${proto}://${host}`;
}

/** Self-contained popup HTML — avoids navigating to auth-guarded pages. */
function successHtml(accessToken?: string): string {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Figma Console — Connected</title>
<style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}body{min-height:100vh;display:flex;align-items:center;justify-content:center;background:#0d0d0d;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}.card{text-align:center;padding:48px 40px;background:#161616;border:1px solid rgba(255,255,255,.08);border-radius:16px;max-width:360px;width:100%}.icon{width:56px;height:56px;border-radius:50%;background:rgba(52,211,153,.12);border:1px solid rgba(52,211,153,.3);display:flex;align-items:center;justify-content:center;margin:0 auto 20px;font-size:24px}h1{font-size:20px;font-weight:600;margin-bottom:8px}.subtitle{font-size:14px;color:rgba(255,255,255,.5);margin-bottom:24px;line-height:1.5}.close-hint{display:none;font-size:13px;color:rgba(255,255,255,.3);background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:10px 16px}</style></head>
<body><div class="card"><div class="icon">✓</div><h1>Connected!</h1><p class="subtitle">Figma Console is now connected.<br>Returning to the plugin…</p><p class="close-hint" id="close-hint">Authentication complete — you can close this tab.</p></div>
<script>
var token = ${JSON.stringify(accessToken ?? null)};
if(token){localStorage.setItem('southleft_access_token',token);}
if(window.opener){try{window.opener.postMessage({type:'southleft-oauth-complete',accessToken:token},'*');}catch(e){}}
window.close();
setTimeout(function(){document.getElementById('close-hint').style.display='block';},200);
</script></body></html>`;
}

export async function GET(request: NextRequest) {
  const cookieStore = await cookies();
  const origin = requestOrigin(request);

  // Per-session key generated by the client, used to match write→poll
  const session = request.nextUrl.searchParams.get("session") || "shared-dev-session";

  const state = crypto.randomBytes(16).toString("hex");

  const pendingCookies: Array<{ name: string; value: string; options: Record<string, unknown> }> = [];

  const provider = await createSouthleftMcpOAuthProvider(
    cookieStore,
    (name, value, options) => {
      pendingCookies.push({ name, value, options });
    },
    state,
    origin,
  );

  const isSecure = origin.startsWith("https");
  const sessionCookieOptions = {
    httpOnly: true,
    secure: isSecure,
    sameSite: "lax" as const,
    path: "/",
    maxAge: 600,
  };

  try {
    await auth(provider, {
      serverUrl: new URL(SOUTHLEFT_MCP_URL),
      scope: "file_content:read,library_content:read,file_variables:read",
    });

    // Tokens already valid — relay to polling via oauth-store
    const existingTokens = await provider.tokens();
    writeOAuthResult(session, {
      type: "southleft-mcp-auth",
      success: true,
      access_token: existingTokens?.access_token,
    });

    // Return self-contained HTML so the popup never navigates to an auth-guarded page
    const html = successHtml(existingTokens?.access_token);
    const response = new NextResponse(html, {
      headers: { "Content-Type": "text/html" },
    });
    response.cookies.delete(COOKIE_OAUTH_SESSION);
    return response;
  } catch (error) {
    if (error instanceof RedirectError) {
      const url = new URL(error.url);
      const redirectState = url.searchParams.get("state") || "";
      const response = new NextResponse(null, {
        status: 307,
        headers: { Location: error.url },
      });

      for (const c of pendingCookies) {
        response.cookies.set(c.name, c.value, c.options as Parameters<typeof response.cookies.set>[2]);
      }

      response.cookies.set(SOUTHLEFT_COOKIE_STATE, redirectState, sessionCookieOptions);
      // Persist session key through the OAuth redirect
      response.cookies.set(COOKIE_OAUTH_SESSION, session, sessionCookieOptions);

      return response;
    }

    console.error("[Southleft MCP OAuth] Auth error:", error);
    return NextResponse.json({ error: "OAuth initialization failed" }, { status: 500 });
  }
}
